# urls.py - Complete URL configuration for the social networking API

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router for ViewSets
router = DefaultRouter()
router.register(r'posts', views.PostViewSet, basename='post')

# Define URL patterns
urlpatterns = [
    # ============================================================================
    # AUTHENTICATION URLS
    # ============================================================================
    path('register/', views.register, name='user-register'),
    path('login/', views.login, name='user-login'),
    path('logout/', views.logout, name='user-logout'),
    path('profile/', views.user_profile, name='user-profile'),

    # ============================================================================
    # PROFILE URLS
    # ============================================================================
    path('profiles/', views.ProfileListView.as_view(), name='profile-list'),
    path('profiles/<int:pk>/', views.ProfileDetailView.as_view(), name='profile-detail'),

    # ============================================================================
    # POST URLS (ViewSet routes)
    # ============================================================================
    # The following URLs are automatically generated by the router:
    # GET    /posts/                    -> List all posts
    # POST   /posts/                    -> Create new post
    # GET    /posts/{id}/               -> Retrieve specific post
    # PUT    /posts/{id}/               -> Update specific post
    # PATCH  /posts/{id}/               -> Partial update specific post
    # DELETE /posts/{id}/               -> Delete specific post
    # POST   /posts/{id}/like/          -> Like a post
    # POST   /posts/{id}/unlike/        -> Unlike a post

    # ============================================================================
    # CONNECTION URLS
    # ============================================================================
    path('connections/', views.user_connections, name='user-connections'),
    path('users/<int:user_id>/follow/', views.follow_user, name='follow-user'),
    path('users/<int:user_id>/unfollow/', views.unfollow_user, name='unfollow-user'),

    # ============================================================================
    # RECOMMENDATION URLS
    # ============================================================================
    path('recommendations/', views.user_recommendations, name='user-recommendations'),
    path('recommendations/feedback/', views.recommendation_feedback, name='recommendation-feedback'),
    path('recommendations/refresh/', views.refresh_recommendations, name='refresh-recommendations'),

    path('test-token/', views.test_token, name='test-token'),

    # ============================================================================
    # ROUTER URLS (Include ViewSet routes)
    # ============================================================================
    path('api/', include(router.urls)),
]


