# Generated by Django 5.2.1 on 2025-05-30 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, help_text="Comma-separated interests (e.g., 'photography, travel, cooking')", max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_in_recommendations',
            field=models.BooleanField(default=True, help_text='Allow others to see you in their recommendations'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Overall recommendation score (0.0 to 1.0)')),
                ('mutual_connections_count', models.IntegerField(default=0, help_text='Number of mutual connections')),
                ('common_interests_count', models.IntegerField(default=0, help_text='Number of common interests')),
                ('reason', models.CharField(blank=True, help_text="Why this user was recommended (e.g., '3 mutual connections, 2 common interests')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_user', models.ForeignKey(help_text='User being recommended', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='Backend.profile')),
                ('user', models.ForeignKey(help_text='User who will see this recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='Backend.profile')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'recommended_user')},
            },
        ),
    ]
